/* eslint-disable */

/**
 * List of non-inheritable properties.
 *
 * Borrowed from https://github.com/suitcss/preprocessor/blob/master/lib/encapsulation.js
 */
export default {
  animation: 'none 0s ease 0s 1 normal none running',
  'backface-visibility': 'visible',
  background: 'transparent none repeat 0 0 / auto auto padding-box border-box scroll',
  border: 'medium none currentColor',
  'border-image': 'none',
  'border-radius': '0',
  bottom: 'auto',
  'box-shadow': 'none',
  clear: 'none',
  clip: 'auto',
  columns: 'auto',
  'column-count': 'auto',
  'column-fill': 'balance',
  'column-gap': 'normal',
  'column-rule': 'medium none currentColor',
  'column-span': '1',
  'column-width': 'auto',
  content: 'normal',
  'counter-increment': 'none',
  'counter-reset': 'none',
  float: 'none',
  height: 'auto',
  hyphens: 'none',
  left: 'auto',
  margin: '0',
  'max-height': 'none',
  'max-width': 'none',
  'min-height': '0',
  'min-width': '0',
  opacity: '1',
  outline: 'medium none invert',
  overflow: 'visible',
  'overflow-x': 'visible',
  'overflow-y': 'visible',
  padding: '0',
  'page-break-after': 'auto',
  'page-break-before': 'auto',
  'page-break-inside': 'auto',
  perspective: 'none',
  'perspective-origin': '50% 50%',
  position: 'static',
  right: 'auto',
  'table-layout': 'auto',
  'text-decoration': 'none',
  top: 'auto',
  transform: 'none',
  'transform-origin': '50% 50% 0',
  'transform-style': 'flat',
  transition: 'none 0s ease 0s',
  'unicode-bidi': 'normal',
  'vertical-align': 'baseline',
  width: 'auto',
  'z-index': 'auto'
};